version: '3.3'
services:
  db:
    container_name: hello.db
    image: postgres:10.3-alpine    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456    

  web:    
    image: helderboone/ecommerce    
    build:
      context: .
      dockerfile: src/Ecommerce.Web/Dockerfile
    restart: always    
    depends_on:
      - db
    links:
      - db    
  
  web2:    
    image: helderboone/ecommerce    
    build:
      context: .
      dockerfile: src/Ecommerce.Web/Dockerfile
    restart: always    
    depends_on:
      - db
    links:
      - db  

  web3:    
    image: helderboone/ecommerce    
    build:
      context: .
      dockerfile: src/Ecommerce.Web/Dockerfile
    restart: always    
    depends_on:
      - db
    links:
      - db  
      
  web4:    
    image: helderboone/ecommerce    
    build:
      context: .
      dockerfile: src/Ecommerce.Web/Dockerfile
    restart: always    
    depends_on:
      - db
    links:
      - db

  reverse-proxy:
    container_name: hello.proxy
    image: nginx:1.13.12
    depends_on:
      - web
      - web2
      - web3
      - web4
    links:
      - web
      - web2
      - web3
      - web4  
    ports:
      - "8080:8080"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf    
